# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_raw.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_root(object):
    def setupUi(self, root):
        root.setObjectName("root")
        root.resize(1359, 765)
        root.setMinimumSize(QtCore.QSize(1359, 765))
        root.setMaximumSize(QtCore.QSize(1359, 765))
        self.centralwidget = QtWidgets.QWidget(root)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_inputs = QtWidgets.QFrame(self.centralwidget)
        self.frame_inputs.setGeometry(QtCore.QRect(0, 0, 401, 751))
        self.frame_inputs.setStyleSheet("background-color: rgb(24, 135, 157);")
        self.frame_inputs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inputs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inputs.setObjectName("frame_inputs")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame_inputs)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 381, 328))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.FormLayout_inputs = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.FormLayout_inputs.setContentsMargins(0, 0, 0, 0)
        self.FormLayout_inputs.setVerticalSpacing(8)
        self.FormLayout_inputs.setObjectName("FormLayout_inputs")
        self.lbl_trabajadorID = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_trabajadorID.setObjectName("lbl_trabajadorID")
        self.FormLayout_inputs.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_trabajadorID)
        self.txt_trabajadorID = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_trabajadorID.setPlaceholderText("")
        self.txt_trabajadorID.setObjectName("txt_trabajadorID")
        self.FormLayout_inputs.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_trabajadorID)
        self.lbl_fechaIngreso = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_fechaIngreso.setObjectName("lbl_fechaIngreso")
        self.FormLayout_inputs.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_fechaIngreso)
        self.txt_fechaIngreso = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_fechaIngreso.setObjectName("txt_fechaIngreso")
        self.FormLayout_inputs.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_fechaIngreso)
        self.lbl_TipoTrab = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_TipoTrab.setObjectName("lbl_TipoTrab")
        self.FormLayout_inputs.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_TipoTrab)
        self.txt_tipoTrabajador = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_tipoTrabajador.setObjectName("txt_tipoTrabajador")
        self.FormLayout_inputs.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_tipoTrabajador)
        self.lbl_valorHora = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_valorHora.setObjectName("lbl_valorHora")
        self.FormLayout_inputs.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_valorHora)
        self.txt_valorHora = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_valorHora.setObjectName("txt_valorHora")
        self.FormLayout_inputs.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txt_valorHora)
        self.lbl_horasSimples = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_horasSimples.setObjectName("lbl_horasSimples")
        self.FormLayout_inputs.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_horasSimples)
        self.txt_hs_simples = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_hs_simples.setObjectName("txt_hs_simples")
        self.FormLayout_inputs.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txt_hs_simples)
        self.lbl_horasExtras = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_horasExtras.setObjectName("lbl_horasExtras")
        self.FormLayout_inputs.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_horasExtras)
        self.txt_hs_Ext = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_hs_Ext.setObjectName("txt_hs_Ext")
        self.FormLayout_inputs.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txt_hs_Ext)
        self.lbl_horas_ext_esp = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_horas_ext_esp.setObjectName("lbl_horas_ext_esp")
        self.FormLayout_inputs.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbl_horas_ext_esp)
        self.txt_hs_ext_esp = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_hs_ext_esp.setObjectName("txt_hs_ext_esp")
        self.FormLayout_inputs.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txt_hs_ext_esp)
        self.lbl_horasNoc = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_horasNoc.setObjectName("lbl_horasNoc")
        self.FormLayout_inputs.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lbl_horasNoc)
        self.txt_horas_noc = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_horas_noc.setObjectName("txt_horas_noc")
        self.FormLayout_inputs.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txt_horas_noc)
        self.lbl_jornada_esp = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_jornada_esp.setObjectName("lbl_jornada_esp")
        self.FormLayout_inputs.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lbl_jornada_esp)
        self.txt_jornadaEsp = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_jornadaEsp.setObjectName("txt_jornadaEsp")
        self.FormLayout_inputs.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.txt_jornadaEsp)
        self.label = QtWidgets.QLabel(self.frame_inputs)
        self.label.setGeometry(QtCore.QRect(10, 5, 191, 21))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_inputs)
        self.label_2.setGeometry(QtCore.QRect(10, 340, 91, 41))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif\";")
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.frame_inputs)
        self.line.setGeometry(QtCore.QRect(10, 320, 381, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.frame_inputs)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 370, 381, 242))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lbl_BPS = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_BPS.setObjectName("lbl_BPS")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_BPS)
        self.txt_bps = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txt_bps.setObjectName("txt_bps")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_bps)
        self.lbl_fonasa = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_fonasa.setObjectName("lbl_fonasa")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_fonasa)
        self.txt_fonasa = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txt_fonasa.setObjectName("txt_fonasa")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_fonasa)
        self.lbl_frl = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_frl.setObjectName("lbl_frl")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_frl)
        self.txt_frl = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txt_frl.setObjectName("txt_frl")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_frl)
        self.lbl_hijosCargo = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_hijosCargo.setObjectName("lbl_hijosCargo")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_hijosCargo)
        self.txt_hijos = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txt_hijos.setObjectName("txt_hijos")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txt_hijos)
        self.lbl_discapacitados = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_discapacitados.setObjectName("lbl_discapacitados")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_discapacitados)
        self.txt_discapacitados = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txt_discapacitados.setObjectName("txt_discapacitados")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txt_discapacitados)
        self.lbl_conyuge = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_conyuge.setObjectName("lbl_conyuge")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_conyuge)
        self.lbl_cony_disca = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_cony_disca.setObjectName("lbl_cony_disca")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lbl_cony_disca)
        self.checkBox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.checkBox)
        self.chbox_conyuge = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        self.chbox_conyuge.setObjectName("chbox_conyuge")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.chbox_conyuge)
        self.btn_liquidarIndividual = QtWidgets.QPushButton(self.frame_inputs)
        self.btn_liquidarIndividual.setGeometry(QtCore.QRect(10, 650, 381, 71))
        self.btn_liquidarIndividual.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_liquidarIndividual.setObjectName("btn_liquidarIndividual")
        self.frame_monitor_tabla = QtWidgets.QFrame(self.centralwidget)
        self.frame_monitor_tabla.setGeometry(QtCore.QRect(400, 0, 961, 431))
        self.frame_monitor_tabla.setStyleSheet("background-color: rgb(19, 163, 206);")
        self.frame_monitor_tabla.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_monitor_tabla.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_monitor_tabla.setObjectName("frame_monitor_tabla")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_monitor_tabla)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 941, 401))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.frame_botonesYcontroladores = QtWidgets.QFrame(self.centralwidget)
        self.frame_botonesYcontroladores.setGeometry(QtCore.QRect(400, 430, 961, 321))
        self.frame_botonesYcontroladores.setStyleSheet("background-color: rgb(11, 179, 197);")
        self.frame_botonesYcontroladores.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_botonesYcontroladores.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_botonesYcontroladores.setObjectName("frame_botonesYcontroladores")
        self.btn_mostrarTrabajadores = QtWidgets.QPushButton(self.frame_botonesYcontroladores)
        self.btn_mostrarTrabajadores.setGeometry(QtCore.QRect(10, 220, 271, 71))
        self.btn_mostrarTrabajadores.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_mostrarTrabajadores.setObjectName("btn_mostrarTrabajadores")
        self.line_2 = QtWidgets.QFrame(self.frame_botonesYcontroladores)
        self.line_2.setGeometry(QtCore.QRect(290, 220, 21, 71))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.btn_liquidarBaseDatos = QtWidgets.QPushButton(self.frame_botonesYcontroladores)
        self.btn_liquidarBaseDatos.setGeometry(QtCore.QRect(310, 220, 341, 71))
        self.btn_liquidarBaseDatos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_liquidarBaseDatos.setObjectName("btn_liquidarBaseDatos")
        self.progressBar = QtWidgets.QProgressBar(self.frame_botonesYcontroladores)
        self.progressBar.setGeometry(QtCore.QRect(680, 220, 271, 71))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_botonesYcontroladores)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 941, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_liquido = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_liquido.setObjectName("lbl_liquido")
        self.gridLayout.addWidget(self.lbl_liquido, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Sans Serif\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 18pt \"Sans Serif\";")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.lbl_depositoTrabajadores = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_depositoTrabajadores.setObjectName("lbl_depositoTrabajadores")
        self.gridLayout.addWidget(self.lbl_depositoTrabajadores, 1, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.frame_botonesYcontroladores)
        self.line_3.setGeometry(QtCore.QRect(10, 200, 941, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.frame_botonesYcontroladores)
        self.line_4.setGeometry(QtCore.QRect(650, 220, 21, 71))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        root.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(root)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1359, 20))
        self.menubar.setObjectName("menubar")
        self.menuGestionar_Base_de_Datos = QtWidgets.QMenu(self.menubar)
        self.menuGestionar_Base_de_Datos.setObjectName("menuGestionar_Base_de_Datos")
        self.menuLiquidacion_Automatica = QtWidgets.QMenu(self.menubar)
        self.menuLiquidacion_Automatica.setObjectName("menuLiquidacion_Automatica")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        root.setMenuBar(self.menubar)
        self.actionAbrir_Base_de_Datos = QtWidgets.QAction(root)
        self.actionAbrir_Base_de_Datos.setObjectName("actionAbrir_Base_de_Datos")
        self.actionProgramar = QtWidgets.QAction(root)
        self.actionProgramar.setObjectName("actionProgramar")
        self.actionComo_funciona_SILIS = QtWidgets.QAction(root)
        self.actionComo_funciona_SILIS.setObjectName("actionComo_funciona_SILIS")
        self.actionCreditos = QtWidgets.QAction(root)
        self.actionCreditos.setObjectName("actionCreditos")
        self.menuGestionar_Base_de_Datos.addAction(self.actionAbrir_Base_de_Datos)
        self.menuLiquidacion_Automatica.addAction(self.actionProgramar)
        self.menuAyuda.addAction(self.actionComo_funciona_SILIS)
        self.menuAyuda.addAction(self.actionCreditos)
        self.menubar.addAction(self.menuGestionar_Base_de_Datos.menuAction())
        self.menubar.addAction(self.menuLiquidacion_Automatica.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(root)
        QtCore.QMetaObject.connectSlotsByName(root)

    def retranslateUi(self, root):
        _translate = QtCore.QCoreApplication.translate
        root.setWindowTitle(_translate("root", "SILIS v4"))
        self.lbl_trabajadorID.setText(_translate("root", "Trabajador ID"))
        self.lbl_fechaIngreso.setText(_translate("root", "Fecha de Ingreso"))
        self.lbl_TipoTrab.setText(_translate("root", "Tipo de Trabajador"))
        self.lbl_valorHora.setText(_translate("root", "Valor de la Hora"))
        self.lbl_horasSimples.setText(_translate("root", "Horas Simples"))
        self.lbl_horasExtras.setText(_translate("root", "Horas Extras"))
        self.lbl_horas_ext_esp.setText(_translate("root", "Horas Extras Especiales"))
        self.lbl_horasNoc.setText(_translate("root", "Horas Nocturnas"))
        self.lbl_jornada_esp.setText(_translate("root", "Jornada Especial"))
        self.label.setText(_translate("root", "Datos del Trabajador"))
        self.label_2.setText(_translate("root", "Deducciones"))
        self.lbl_BPS.setText(_translate("root", "BPS"))
        self.lbl_fonasa.setText(_translate("root", "FONASA"))
        self.lbl_frl.setText(_translate("root", "FRL"))
        self.lbl_hijosCargo.setText(_translate("root", "Hijos a Cargo"))
        self.lbl_discapacitados.setText(_translate("root", "Discapacitados"))
        self.lbl_conyuge.setText(_translate("root", "Conyuge a cargo"))
        self.lbl_cony_disca.setText(_translate("root", "Conyuge Discapacitado"))
        self.checkBox.setText(_translate("root", "Si"))
        self.chbox_conyuge.setText(_translate("root", "Si"))
        self.btn_liquidarIndividual.setText(_translate("root", "Liquidar Individual"))
        self.btn_mostrarTrabajadores.setText(_translate("root", "Mostrar Trabajadores"))
        self.btn_liquidarBaseDatos.setText(_translate("root", "Liquidar todos los Trabajadores"))
        self.lbl_liquido.setText(_translate("root", "TextLabel"))
        self.label_3.setText(_translate("root", "LIQUIDO:"))
        self.label_5.setText(_translate("root", "Total deposito a los los Trabajadores:"))
        self.lbl_depositoTrabajadores.setText(_translate("root", "TextLabel"))
        self.menuGestionar_Base_de_Datos.setTitle(_translate("root", "Gestionar Base de Datos"))
        self.menuLiquidacion_Automatica.setTitle(_translate("root", "Liquidacion Automatica"))
        self.menuAyuda.setTitle(_translate("root", "Ayuda"))
        self.actionAbrir_Base_de_Datos.setText(_translate("root", "Abrir Base de Datos"))
        self.actionProgramar.setText(_translate("root", "Programar..."))
        self.actionComo_funciona_SILIS.setText(_translate("root", "Como funciona SILIS?"))
        self.actionCreditos.setText(_translate("root", "Creditos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    root = QtWidgets.QMainWindow()
    ui = Ui_root()
    ui.setupUi(root)
    root.show()
    sys.exit(app.exec_())
